export default {
  CREATE_POST: 'CREATE_POST',
  EDIT_POST: 'EDIT_POST',
  UPDATE_POST: 'UPDATE_POST',
  DELETE_POST: 'DELETE_POST',
  NEW_POST_TITLE_CHANGE: 'NEW_POST_TITLE_CHANGE',
  NEW_POST_BODY_CHANGE: 'NEW_POST_BODY_CHANGE',
};